### ISSUE TITLE
Reusable block isn't resolved inside columns

### ISSUE THREAD

**Issue by MKlblangenois** [wpengine/wp-graphql-content-blocks#184] opened 2024-02-05 09:55 UTC
When I try to make a query to resolve innerBlocks of Core/Block (reusable block), I only got `renderedHtml`, but it doesn't resolve innerBlocks or attributes, but when I use it inside root of Gutenberg, GraphQL resolve innerBlocks block to display them as `root` too.

![SCR-20240205-jtol](https://github.com/wpengine/wp-graphql-content-blocks/assets/42929225/0dd4b5b2-0966-4aec-8b86-13d352110c31)

**Step to reproduce:**

1. Create a block (on my case : heading + paragraph and group them)
2. Save it has reusable
3. Add a columns block
4. Insert reusable block inside one column

This is what it looks like used on the same page:
![SCR-20240205-jwnv](https://github.com/wpengine/wp-graphql-content-blocks/assets/42929225/2cbc1810-3f98-4f67-8e4c-8546510e6b90)

<details> 
        <summary><strong>GraphQL result</strong></summary> 

```json
{
  "data": {
    "testPage": {
      "editorBlocks": [
        {
          "name": "core/group",
          "innerBlocks": [
            {
              "name": "core/heading",
              "innerBlocks": []
            },
            {
              "name": "core/paragraph",
              "innerBlocks": []
            },
            {
              "name": "core/buttons",
              "innerBlocks": [
                {
                  "name": "core/button",
                  "innerBlocks": []
                },
                {
                  "name": "core/button",
                  "innerBlocks": []
                },
                {
                  "name": "core/button",
                  "innerBlocks": []
                },
                {
                  "name": "core/button",
                  "innerBlocks": []
                }
              ]
            }
          ]
        },
        {
          "name": "core/columns",
          "innerBlocks": [
            {
              "name": "core/column",
              "innerBlocks": [
                {
                  "name": "core/paragraph",
                  "innerBlocks": []
                }
              ]
            },
            {
              "name": "core/column",
              "innerBlocks": [
                {
                  "name": "core/block",
                  "innerBlocks": []
                }
              ]
            }
          ]
        },
      ]
    }
  },
}
```
</details>       

**Version**:
- wp-graphql-content-blocks: 2.0.0
- Faust.js: 1.2.1
- WPGraphQL: 1.20.0

**Comment by theodesp** [comment] 2024-02-06 12:35
hey @MKlblangenois did you try removing the (flat:  false) there?
It should be `editorBlocks` instead of `editorBlocks(flat:  false)`

**Comment by theodesp** [comment] 2024-02-06 12:39
Hey @MKlblangenois I think reusable blocks only resolve when using the `editorBlocks` field instead of the `editorBlocks(flat: false) which you are using.

See: https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/Data/ContentBlocksResolver.php#L57-L68

**Comment by theodesp** [comment] 2024-03-12 15:04
@MKlblangenois were you able to fix your issues?

**Comment by justlevine** [comment] 2024-03-12 15:33
> Hey @MKlblangenois I think reusable blocks only resolve when using the `editorBlocks` field instead of the `editorBlocks(flat: false)` which you are using.
> 
> See: https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/Data/ContentBlocksResolver.php#L57-L68

@theodesp is that a bug, known limitation, or intended behavior?

If it's one of the latter two, can this be documented somewhere? (If it is already, I can't find it)

**Comment by theodesp** [comment] 2024-06-27 10:51
Hey @MKlblangenois Thanks for the report. I will provide a fix for this.

**Closed** 2024-07-02 14:03 UTC
Labels: bug
