### ISSUE TITLE
Why was `WPGraphQL\ContentBlocks\Blocks\Block::register_fields()` removed.

### ISSUE THREAD

**Issue by kidunot89** [wpengine/wp-graphql-content-blocks#121] opened 2023-06-21 22:33 UTC
# Summary
I have been using [this functionality](https://github.com/wpengine/wp-graphql-content-blocks/blame/eb8e3641f0cd76ddbcad153f6a555d19bc5d8c02/includes/Blocks/Block.php#L87) for quite sometime now, and it was removed in `v0.3.0` with no documentation or explanation I can find anywhere.

Here is a block I have that was broken when I updated to `v1.0.0`
```php
/**
 * Product_And_Cart_Block class.
 */
class Product_And_Cart_Block extends Block {
	/**
	 * Registers GraphQL fields to the ProductAndCartAttributes type.
	 *
	 * @return void
	 */
	public function register_fields() {
		$this->block_registry->type_registry->register_fields(
			$this->type_name,
			[
				'selectedProduct' => [
					'type'        => 'Product',
					'description' => __( 'The alignment of the block', 'probable-doodle' ),
					'resolve'     => function( $block, $args, $context ) {
						$product_id = $block['attrs']['product'] ?? null;
						// Resolve product if ID found.
						if ( absint( $product_id ) ) {
							return $context->get_loader( 'wc_post' )->load( absint( $product_id ) );
						}
						return null;
					},
				],
			]
		);
	}
}
```
Is this functionality no longer supported. If not, what is the alternative to this functionality?

**Comment by mindctrl** [comment] 2023-06-22 15:49
Hey @kidunot89, first I'd like to apologize for the issue you experienced. We forgot to add that to the changelog. Unfortunate considering the type of change it was. We're making some changes to our processes to help avoid making mistakes like this in the future.

The reason we removed that method is because the plugin itself didn't use it for any of the stuff it does, and we were looking to minimize the size of the public API, and we decided that it probably doesn't make sense for us to provide it if we don't even use it internally.

As far as an alternative, I would recommend calling `Product_And_Cart_Block::register_fields()` method yourself, maybe somewhere inside the same class?

We're happy to discuss this decision and consider reverting or coming up with an alternative.

**Comment by kidunot89** [comment] 2023-06-22 16:00
@mindctrl Understood. However, I do believe some functionality like this should be supported.

Lemme explain my use-case. [This page](https://woographql.com/pro) is using three instances of the blocks mentioned in my OP. The reason for the `selectedProduct` field is by registering this direct connection to the `Product` type I can query this data during the static generation step along with the rest of the page content. Without it, I have to product data using the blocks `product` attribute on page load making the page load time balloon.

**Comment by justlevine** [comment] 2023-06-22 16:42
> I can't imagine I'm the only one who will run into this use-case.

@kidunot89 I wasn't aware a copy of the `$type_registry` was even public.

I'm not entirely sure I understand your use case. How is it different than `\WPGraphQL::get_type_registry()->register_fields()` or just `register_graphql_fields()`?


Eg.
```diff
- $this->block_registry->type_registry->register_fields(
- + register_graphql_fields(
	$this->type_name,
	[
		'selectedProduct' => [
			'type'        => 'Product',
			'description' => __( 'The alignment of the block', 'probable-doodle' ),
			'resolve'     => function( $block, $args, $context ) {
				$product_id = $block['attrs']['product'] ?? null;
				// Resolve product if ID found.
				if ( absint( $product_id ) ) {
					return $context->get_loader( 'wc_post' )->load( absint( $product_id ) );
				}
				return null;
			},
		],
	]
);
```

**Comment by kidunot89** [comment] 2023-06-22 16:48
It's not about the how `register_graphql_fields()` gets called, the issue should be on the fact the `Block::register_fields()` never gets called. Or is there a filter with `$this->type_name` used in the constructor. Right now I have to overload the `Block::__construct()` function, which is undesirable.

**Comment by justlevine** [comment] 2023-06-22 20:06
Thanks for clarifying, @kidunot89 !

As someone with a preference for composables, I personally prefer this (where I can wrap Block in my own class, use my own traits/interfaces), especially versus forcing a noop who's intended use isnt dogfed internally and thus more susceptible to regressions. But I get that's a very subjective take.

**Comment by 3lcarry** [comment] 2023-08-03 00:04
If you are not planning to recover this feature, please update the documentation https://faustjs.org/reference/wp-graphql-content-blocks-filters. Maybe adding an action to include custom fields in a easy way without extending the block can be helpful.

**Comment by mindctrl** [comment] 2023-08-03 17:54
Hey folks, we let this sit a while to hear more feedback before revisiting the decision.

@3lcarry thanks for calling out the documentation issue. We'll fix that. I also like the idea of including an action to make things easier. I'll log a separate issue for that.

@justlevine essentially captured our thinking here, and as such we don't think it makes sense to add back. If it turns out we were wrong or things change and we need this sort of API internally, we'll be happy to revisit.

I'll close this for now, but please share any extra thoughts if you have them.

**Closed by mindctrl** 2023-08-03 17:54 UTC
