### ISSUE TITLE
Downloading the plugin as a composer package does not contain the vendor directory and autoloads

### ISSUE THREAD

**Issue by cherrygot-personal** [wpengine/wp-graphql-content-blocks#168] opened 2023-12-08 11:31 UTC
Hi

I recently upgraded my wp-graphql-content-blocks plugin from 1.1.1 to 2.0.0 and the first thing the graphql requests lead to is an exception saying that it can not find WPGraphQLHelpers. 
![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/21972052/d439235f-9a67-4d56-8c83-e99634c5608d)

I checked in the downloaded plugin and saw no vendor/ folder. I checked the composer.json file for PSR-4 autoloads and was able to get it resolved via generating the autoloads for the plugin.

However, when I checked the zip present in the release https://github.com/wpengine/wp-graphql-content-blocks/releases/tag/v2.0.0, there is a vendor folder. So this issue happens only when loading this plugin via composer.

**Comment by theodesp** [comment] 2023-12-11 10:48
Hey @cherrygot-personal currently we do not provision the plugin in packagist or the wordpress plugins registry

**Comment by justlevine** [comment] 2023-12-11 11:36
> Hey @cherrygot-personal currently we do not provision the plugin in packagist or the wordpress plugins registry and you should be using the `releases` tab since the project source code does not contain a `vendor` folder.
> 
> Another option is to just install the composer dependencies by running the `composer install --no-dev` within the plugin folder.

@theodesp is the above an acknowledgement of the bug in how this plugin checks for the existence of it's autoloader (looking for files in a fixed plugin-relative folder), instead of if the autoloaded classes exist) or a clarification about intentional design and intended behavior?

Enterprise- headless sites should really be using Composer to manage their backend dependencies, so I'd assume we'd want to reduce that friction as much as possible?

**Comment by theodesp** [comment] 2023-12-11 15:01
> Composer

Hey @justlevine we do have Composer for managing backend dependencies but we don't ship them as part of the source code.

I'm not familiar with the proper conventions here but my assumption is that `vendor` folder is similar to `node_modules` folder and should not be part of the git repo.

**Comment by justlevine** [comment] 2023-12-11 15:15
The issue isn't about storing the `vendor` folder in .git, it's that when composer _installs a library_ (whether it's from git or packagist or a release zip), the library's dependencies get installed in the top-level `vendor` folder.

Because `wp-graphql-content-blocks` checks for explicit files in the `mysite/wp-content/plugins/wp-graphql-content-blocks/vendor` folder, users who are using composer to manage their WordPress build (as they should in Enterprise) are mistakenly told they don't have the deps, even though they just exist in a top-level path (e.g. `my-site/wp-content/vendor` ).

Since you're using Composer internally, you can skip the file-check, and instead check if the autoloaded class exists. I wouldn't copy it verbatim, but if you're looking for inspiration, see how WPGraphQL core [handles it](https://github.com/wp-graphql/wp-graphql/blob/1051357687339e53b7bd19b816c756316dbc8a47/wp-graphql.php#L72)

**Comment by cherrygot-personal** [comment] 2023-12-11 16:16
@theodesp

I agree, I checked my composer file again and it is indeed not loaded from some package registry like packagist or wpackagist. I'm using it just like justlevine, via repositories property with type github.
```json
{  ...
    "repositories": [
          ...
          {
                "type": "github",
                "url": "<repo-url>"
          }
          ...
    ]
    ....
}
```

 So this does make sense that you wouldn't go for git track `vendor/`, just like you wouldn't do so for `node_modules/`.
 
 So two solutions come to mind,
 1. We put the plugin on a registry. Well, that's something I have no idea how to do. (But love to give it a try)
 2. We use some sort of lifecycle hook and run the autoload dump command. 
 
 I'm using the second approach at the moment, but in my project repo, like so
 ```
 "scripts": {
     "post-install-cmd": [
          "cd wordpress/web/app/mu-plugins/wp-graphql-content-blocks/; composer dump-autoload -o",
          ...
     ]
 }
 ```
 
My idea, not sure how feasible though, is to hook the dump autoload command to the life-cycle of the repo instead of it being the burden of the consumer of the repo. Again, that's just a fancy idea, I'm not sure if that's how composer can work.


@justlevine I have not tried using it as a normal plugin via composer. Like I've used it as normal plugin by downloading zip from the release page, but not as composer dependency. But there's a quick fix for it so I never bothered to try that. I mentioned it because, as you said, big budget applications using composer will face this problem too.

And btw, thanks for the info, I didn't know that autoloads are generated at root level "vendor/" directory. I checked and there is a mapping to the includes/ folder of the repo like so,
```php
return array(
    'WPGraphQL\\ContentBlocks\\' => array($baseDir . '/wordpress/web/app/mu-plugins/wp-graphql-content-blocks/includes'),
    ...
);
```
So I'm a bit surprised why this would be happening. The reason why I'm not thinking that it may have to do something with it being an mu-plugin is because I'm using `wp-graphql` as mu-plugin as well, it resolves just fine.

**Comment by justlevine** [comment] 2023-12-11 16:57
@cherrygot-personal 
> So two solutions come to mind,
> 
> 1. We put the plugin on a registry. Well, that's something I have no idea how to do. (But love to give it a try)

`composer install my-package-from-registry` will still install any `composer.json` deps in the package in to a top-level `vendor`, so this won't solve the problem.

> I checked and there is a mapping to the includes/ folder of the repo like so,
> [...]
> So I'm a bit surprised why this would be happening. The reason why I'm not thinking that it may have to do something with it being an mu-plugin is because I'm using `wp-graphql` as mu-plugin as well, it resolves just fine.

Just because one plugin works well as an mu-plugin doesnt mean another one will. Ultimately it comes down to a race condition about when the mu-plugin loads vs when Composer's autoloader gets injected. Bonus, it only takes a few minutes to try and rule out 😇.

As a general rule you should `mu-plugins` for custom plugins and install actual plugins as regular `plugins` (you can use an mu-plugin to _force-activate_ a plugin, but I can't imagine a situation where you wouldn't want the ability to disable a plugin (e.g. for debugging).

**Comment by theodesp** [comment] 2023-12-12 12:14
> The issue isn't about storing the `vendor` folder in .git, it's that when composer _installs a library_ (whether it's from git or packagist or a release zip), the library's dependencies get installed in the top-level `vendor` folder.
> 
> Because `wp-graphql-content-blocks` checks for explicit files in the `mysite/wp-content/plugins/wp-graphql-content-blocks/vendor` folder, users who are using composer to manage their WordPress build (as they should in Enterprise) are mistakenly told they don't have the deps, even though they just exist in a top-level path (e.g. `my-site/wp-content/vendor` ).
> 
> Since this plugin uses Composer internally, we can skip the file-check, and instead check if the autoloaded class exists. I wouldn't copy it verbatim, but if you're looking for inspiration, see how WPGraphQL core [handles it](https://github.com/wp-graphql/wp-graphql/blob/1051357687339e53b7bd19b816c756316dbc8a47/wp-graphql.php#L72)

We do something similar here:

https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/WPGraphQLContentBlocks.php#L95-L150

is something we are missing?

**Comment by cherrygot-personal** [comment] 2023-12-12 16:11
@justlevine I tried installing as a plugin and the same issue pops up.
```
[12-Dec-2023 16:06:21 UTC] PHP Fatal error:  Uncaught Error: Class "WPGraphQL\ContentBlocks\Utilities\WPGraphQLHelpers" not found in /var/www/wordpress/web/app/plugins/wp-graphql-content-blocks/includes/Registry/Registry.php:224
```

**Comment by justlevine** [comment] 2023-12-12 16:37
> @justlevine I tried installing as a plugin and the same issue pops up. [...] And the admin notice too

Admin notice is the aforementioned bug, nothing you can do on your end to fix.

If the still doesnt exist by the time you're loading your plugins, then it points to a problem with your Composer config. To debug, I'd suggest the following steps:

1. Run `composer dump-autoload --no-dev --optimize` (in case any of your previous troubleshooting threw it for some loops).
2. Delete your dependencies (_including your composer-installed plugins_), and run `composer install --no-dev --optimize-autoloader` (sometimes Composer gets tripped up by caching when the deps arent in the normal `vendor` dir).

If you're _still_ running into issues, the bug isn't with Composer (which is how the `Registry` class gets loaded so it's currently _partially_ working), and will require some investigation.

**Comment by cherrygot-personal** [comment] 2024-01-13 16:17
Hey @justlevine , sorry for responding late on this issue.

So yeah, I went through the checklist and first deleted all the dependencies in vendor/ and installed plugins, and then generated autoloads. Still, no luck :/

Tried changing the github to vcs, but the issue remains the same.

However, this issue is turning out to be a very strange one for me. And looks like an edge case that makes me doubt if it's very specific to my machine or something. Here's what I found:

When I replace the `WPGraphQLHelpers` name with something else, let's say `TestHelpers` and the file to TestHelpers.php, the thing works absolutely fine. No exceptions, warnings or errors. All that with just one name change. Just to make sure that it's not conflicting with any class names that I've defined locally, I ran a search in my work folder and I found nothing suspicious. 

![image](https://github.com/wpengine/wp-graphql-content-blocks/assets/21972052/1a5a010f-387d-4863-9c7e-aa4e1f1ed1f2)

Even if I, let's say, generate the autoloads for the plugin in its directory and remove this line from $classMap array, 
```php
        'WPGraphQL\\ContentBlocks\\Utilities\\WPGraphQLHelpers' => __DIR__ . '/../..' . '/includes/Utilities/WPGraphqlHelpers.php',
```
it starts going haywire. Is this even reproduce-able?

**Comment by cherrygot-personal** [comment] 2024-01-13 17:05
Okay, found the culprit. The file https://github.com/wpengine/wp-graphql-content-blocks/blob/main/includes/Utilities/WPGraphqlHelpers.php doesn't follow PSR4 standards.

The name of the file should be `WPGraphQLHelpers.php` instead of `WPGraphqlHelpers.php`.

**Comment by cherrygot-personal** [comment] 2024-02-28 05:34
Hey everyone, 

I see that there is a v3.0.0 release of the plugin. I was wondering if this issue can be taken into account for the next patch release? As for the summary, justlevine's comment about not needing vendor/ in the repo makes sense, since composer will automatically resolve it. So we don't need the vendor directory as such. 

The solution for this issue mentioned in my screenshot is just to rename the file `WPGraphqlHelpers.php` to `WPGraphQLHelpers.php`. It'd be great that it's considered.

Thanks :)

**Comment by mindctrl** [comment] 2024-03-04 19:24
@cherrygot-personal we just merged https://github.com/wpengine/wp-graphql-content-blocks/pull/201 with this fix. It'll be in the next release. Thanks for reporting this and for your patience.

**Closed** 2024-03-04 19:23 UTC
Labels: bug, good first issue, help wanted
